### ISSUE TITLE
UI界面颜色会变黑

### ISSUE THREAD

**Issue by lz520520** [ganlvtech/down_52pojie_cn#11]
刚搭建好的时候是和爱盘一样的，后面不知道为啥访问后，过几秒背景啥的全变黑了，这个应该哪里修改，我看了js文件，但有点乱，没看到哪里可以改。

**Comment by ganlvtech** [comment]
在 main.js 中去掉 easter-eggs/halloween 的调用

https://github.com/ganlvtech/down_52pojie_cn/blob/7e0e51ef88477a31d1537c3231de9a3cca9028c8/src/main.js#L14-L21

**Comment by lz520520** [comment]
我下载用的release，和code部分的目录文件结构不一样了

**Comment by ganlvtech** [comment]
在 js 文件中搜索那几个字符串

https://github.com/ganlvtech/down_52pojie_cn/blob/aef2625e059ecc06d129cdca9b1631e12a18ac00/js/app.18b1fda0.js#L72

`if("0401"===t||"1030"===t||"1031"===t||"1101"===t){var r=n("2043");r.init()}`

把 `r.init()` 去掉就可以了。

也可以把 `if("0401"===t||"1030"===t||"1031"===t||"1101"===t)` 改成 `if(false)`

**Comment by lz520520** [comment]
可以了，多谢大佬解答，辛苦啦
