### ISSUE TITLE
吾爱破解爱盘 Chrome 浏览器报 dangerous

### ISSUE THREAD

**Issue by qinyihao** [ganlvtech/down_52pojie_cn#16]
![image](https://user-images.githubusercontent.com/40647091/86502405-5762d500-bdd5-11ea-939e-e119e03811db.png)
![image](https://user-images.githubusercontent.com/40647091/86502409-5e89e300-bdd5-11ea-8edc-154a415c27b3.png)

附上windows winver界面：
![image](https://user-images.githubusercontent.com/40647091/86502422-75c8d080-bdd5-11ea-9f2e-c378ca2b26cf.png)

**Comment by ganlvtech** [comment]
这个不是网页的问题，而是下载的文件可能会报毒，导致整个网站被 Google 报毒。这个问题的解决方案是让吾爱破解把有问题的文件加密码保存
