### ISSUE TITLE
有更详细的部署文档么？

### ISSUE THREAD

**Issue by ghost** [ganlvtech/down_52pojie_cn#18]

**Comment by da-gongren** [comment]
@ganlvtech 代码里是否有需要在线加载的，如果有应该还需要下载下来，网络不好，可能在线加载不了。

**Comment by da-gongren** [comment]
@ganlvtech dist 压缩包里没这个文件，是要手动下么
![image](https://user-images.githubusercontent.com/51149477/112181684-9cff5080-8c37-11eb-884b-ecc72685a805.png)

![image](https://user-images.githubusercontent.com/51149477/112181765-abe60300-8c37-11eb-8904-a15ca3bd3c6b.png)

**Comment by da-gongren** [comment]
![image](https://user-images.githubusercontent.com/51149477/112181982-dcc63800-8c37-11eb-9580-d90df6b85c18.png)

这个也没有呢

另外这个爬虫和扫描是只在部署时执行一次，后面新加入的文件会自动生成索引么

**Comment by ganlvtech** [comment]
家里用不用搜索的话，直接在对应的目录执行 php -S 0.0.0.0:8000 就可以 在 http://127.0.0.1:8000 访问了，不用那么麻烦。
 爱盘这么做是因为要考虑使用 nginx 做静态网站，优化 SEO，又要考虑用户搜索，所以才提前通过 php 扫描程序，扫描文件列表，加一个索引的。
