### ISSUE TITLE
代码还有彩蛋么？

### ISSUE THREAD

**Issue by xiaofanshifu** [ganlvtech/down_52pojie_cn#19]
愚人节全黑的？

昨天还好好的😂

**Comment by weifancloud** [comment]
![image](https://user-images.githubusercontent.com/57950591/113232758-5b724380-92d0-11eb-8d34-7bc9518f187a.png)

怎么万圣节呢...

**Comment by weifancloud** [comment]
请问这个 css、js 有没有 没有混淆加密的呀
![image](https://user-images.githubusercontent.com/57950591/113240492-654f7300-92df-11eb-9ff3-652caca4aaf4.png)

**Comment by ganlvtech** [comment]
https://github.com/ganlvtech/down_52pojie_cn/blob/7e0e51ef88477a31d1537c3231de9a3cca9028c8/src/main.js#L17-L20
