### ISSUE TITLE
爱盘的 waf 拦了所有带有 ".tar" 的 url

### ISSUE THREAD

**Issue by yzqzss** [ganlvtech/down_52pojie_cn#21]
> 不知道站点问题能不能在这儿反馈，但我对吾爱破解论坛不熟，短时间没找到更好的反馈渠道，就在这儿反馈了，如有打扰请见谅。

无意间发现爱盘的 waf 会拦截所有带有 `.tar` 字符串的 URL。
比如：
https://down.52pojie.cn/a.tar.b （正常应该返回404）

waf的拦截规则我没有具体试，`a.tarb` 这样的命名似乎可以通过waf，但 `.tar` `.tar.gz` 这样的后缀名都会被拦掉。

此问题导致以下两个文件无法下载：
- https://down.52pojie.cn/LCG/Sublime.Text.3.Build.3065.Ubuntu.32bit.CracKed.By.Hmily.LCG.tar.bz2
- https://down.52pojie.cn/LCG/Sublime.Text.3.Build.3065.Ubuntu.64bit.CracKed.By.Hmily.LCG.tar.bz2

**Comment by Hmily-LCG** [comment]
我来看看。

**Comment by Hmily-LCG** [comment]
已修复。

**Comment by yzqzss** [comment]
好的，谢谢！
