### ISSUE TITLE
大佬，如何关闭节日效果呀？

### ISSUE THREAD

**Issue by fangxingssss** [ganlvtech/down_52pojie_cn#26]

**Comment by ganlvtech** [comment]
在 `dist/.fancyindex/js/app.b8d42948.js` 中删除 0401 1030 这段代码就行了。
当然你也可以直接把这些字符串改成空字符串，让日期对应不上就行了。

![image](https://github.com/user-attachments/assets/4ac98c70-04cb-4e10-8366-a8a75fc9c496)

你也可以删除这段代码，然后重新使用 `npm run build` 编译。
https://github.com/ganlvtech/down_52pojie_cn/blob/7e0e51ef88477a31d1537c3231de9a3cca9028c8/src/main.js#L14-L21

**Comment by fangxingssss** [comment]
大佬，感谢您的回复，问题解决了，祝您工作顺利，阖家安康
