### ISSUE TITLE
Annotation may lead to misunderstanding

### ISSUE THREAD

**Issue by deximy** [ganlvtech/down_52pojie_cn#6]
`// 描述文件（绝对路径） (config.php, line 11) `

may cause misunderstanding that the string of variable 'DESCRIPTION_FILE' should be an absolute path while it is a relative path in fact.

**Comment by ganlvtech** [comment]
You means change it to '/path/to/description.yml' ?

**Comment by liupuchun** [comment]
作者大大你好~我想问一下有没有apache+php7环境配置文档呢~

**Comment by liupuchun** [comment]
作者大大你好我想问一下有没有apache+php7环境配置文档呢
