### ISSUE TITLE
 php 文件扫描程序说明文档好像没用

### ISSUE THREAD

**Issue by ChinaMoli** [ganlvtech/down_52pojie_cn#8]
缺少vendor/autoload.php这个文件

**Comment by ganlvtech** [comment]
尝试使用 https://github.com/ganlvtech/down_52pojie_cn/releases 中提供的打包好的代码。

如果不能解决，请尽可能提供相关信息，例如你的代码下载方式，代码目录结构，安装方式等。

**Comment by ChinaMoli** [comment]
Parse error: syntax error, unexpected '?' in D:\phpStudy\PHPTutorial\WWW\Pan\php\vendor\symfony\yaml\Parser.php on line 499
什么意思

**Comment by ganlvtech** [comment]
什么意思自己去查。

**Comment by ganlvtech** [comment]
@ChinaMoli 如果没有问题，那么 Issue 将被关闭。
