### ISSUE TITLE
请问你在这个项目中如何实现浏览器前进回退的机制？可以说一下思路或者具体实现的代码吗？

### ISSUE THREAD

**Issue by youling4438** [ganlvtech/down_52pojie_cn#9]
请问你在这个项目中如何实现浏览器前进回退的机制？可以说一下思路或者具体实现的代码吗？

**Comment by ganlvtech** [comment]
`history.pushState`

<https://developer.mozilla.org/en-US/docs/Web/API/History_API>

GitHub Issue is not for asking question. Please search it from Google or submit it on StackOverflow.
